name: CD
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  AWS_REGION: us-east-1
  AWS_SDK_LOAD_CONFIG: true
  APP_MAJOR_VERSION: "0.1"

jobs:
  aws-ecr:
    runs-on: ubuntu-latest
    outputs:
      username: ${{ steps.login-ecr.outputs.docker_username_085438893023_dkr_ecr_us_east_1_amazonaws_com }}
      password: ${{ steps.login-ecr.outputs.docker_password_085438893023_dkr_ecr_us_east_1_amazonaws_com }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          mask-aws-account-id: "yes"
          role-to-assume: arn:aws:iam::085438893023:role/github-actions-whitelabel-iam-role
          role-session-name: githubctions
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: "085438893023"


  docker-image-build:
    strategy:
      matrix:
        arch: 
          - runs-on: ubuntu-latest
            name: amd64
          - runs-on: arm64-ubuntu-latest-16-cores
            name: arm64
    runs-on: ${{ matrix.arch.runs-on }}
    needs: aws-ecr
    if: github.repository == 'unit-finance/white-label-app-demo-marketing' && github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker login
        uses: docker/login-action@v3
        with:
          ecr: false
          registry: 085438893023.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ needs.aws-ecr.outputs.username }}
          password: ${{ needs.aws-ecr.outputs.password }}
      - name: Build and push
        id: build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 085438893023.dkr.ecr.us-east-1.amazonaws.com/white-label-app-demo-marketing:${{ github.sha }}-${{ matrix.arch.name }}
          cache-from: "type=registry,ref=085438893023.dkr.ecr.us-east-1.amazonaws.com/white-label-app-demo-marketing-cache:${{ matrix.arch.name }}"
          cache-to: "mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=085438893023.dkr.ecr.us-east-1.amazonaws.com/white-label-app-demo-marketing-cache:${{ matrix.arch.name }}"

  docker-push-manifest:
    runs-on: ubuntu-latest
    needs: [aws-ecr, docker-image-build]
    if: github.repository == 'unit-finance/white-label-app-demo-marketing' && github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker login
        uses: docker/login-action@v3
        with:
          ecr: false
          registry: 085438893023.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ needs.aws-ecr.outputs.username }}
          password: ${{ needs.aws-ecr.outputs.password }}
      - name: Create and push manifest
        run: |
          docker buildx imagetools create --tag 085438893023.dkr.ecr.us-east-1.amazonaws.com/white-label-app-demo-marketing:${{ env.APP_MAJOR_VERSION }}.${{ github.run_number }} \
            085438893023.dkr.ecr.us-east-1.amazonaws.com/white-label-app-demo-marketing:${{ github.sha }}-amd64 \
            085438893023.dkr.ecr.us-east-1.amazonaws.com/white-label-app-demo-marketing:${{ github.sha }}-arm64

